#!/bin/sh
# This script is only used for developement. It is removed by the 
# distribution process. 


set -e

OCAMLBUILD=${OCAMLBUILD:="ocamlbuild -tag debug -classic-display \
                          -use-ocamlfind"}

action () 
{
    case $1 in
      default)      $OCAMLBUILD fut.cmx futu.cmx ;;
      tests)        $OCAMLBUILD tests.otarget ;;
      test_jsoo)    shift; jsoo-build "$*" test/test_jsoo.ml
                    ;;
      doc)          shift; pkg-doc $* doc/dev-api.docdir ;;
      api-doc)      shift; pkg-doc $* doc/api.docdir ;;
      backends)     $OCAMLBUILD fut_select.cmxa fut_jsoo.cmxa ;;
      clean)        $OCAMLBUILD -clean ;;
      jsoo)         shift; jsoo-build $* ;;
      *)            $OCAMLBUILD $* ;;
    esac
} 

if [ $# -eq 0 ]; 
then action default ; 
else action $*; fi
