#!/bin/sh

# Usage: build has_native has_unix has_jsoo

set -e 
LOC=`dirname $0`

. $LOC/pkg-builder

NATIVE=$1
UNIX=$2
REACT=$3
JSOO=$4

add lib pkg/META		
add lib src/fut.mli
add lib src/fut.cmti	
add lib src/fut.cmi
add lib src/fut.cmx
add lib src/fut.cma
add lib src/fut.a
add lib src/fut.cmxa
add lib src/fut.cmxs

add lib src/fut_top.ml
add lib src/fut_top.cmi
add lib src/fut_top.cmx
add lib src/fut_top.cma
add lib src/fut_top.a
add lib src/fut_top.cmxa
add lib src/fut_top.cmxs

add lib src/fut_backend.mli
add lib src/fut_backend.cmti
add lib src/fut_backend.cmi 

if [ "$UNIX" != "false" ]; then
    add lib src/futu.mli
    add lib src/futu.cmti
    add lib src/futu.cmi
    add lib src/futu.cmx	
    add lib src/futu.cma
    add lib src/futu.a
    add lib src/futu.cmxa
    add lib src/futu.cmxs

    add lib src/select/fut_select.cma
    add lib src/select/fut_select.a
    add lib src/select/fut_select.cmxa
    add lib src/select/fut_select.cmxs
fi

if [ "$REACT" != "false" ]; then
    add lib src/futr.mli
    add lib src/futr.cmti
    add lib src/futr.cmi
    add lib src/futr.cmx	
    add lib src/futr.cma
    add lib src/futr.a
    add lib src/futr.cmxa
    add lib src/futr.cmxs
fi

if [ "$JSOO" != "false" ]; then 
    add lib src/jsoo/fut_jsoo.cma
    add lib src/jsoo/fut_jsoo.a
    add lib src/jsoo/fut_jsoo.cmxa
    add lib src/jsoo/fut_jsoo.cmxs
fi

add doc README.md
add doc CHANGES.md

build
install fut
