#!/bin/sh

# Usage: build has_native has_jsoo

set -e 
LOC=`dirname $0`

. $LOC/pkg-builder

NATIVE=$1
JSOO=$2

add lib pkg/META		
add lib src/fut.mli
add lib src/fut.cmti	
add lib src/fut.cmi
add lib src/fut.cmx
add lib src/fut.cma
add lib src/fut.a
add lib src/fut.cmxa
add lib src/fut.cmxs

add lib src/fut_unix.mli
add lib src/fut_unix.cmti
add lib src/fut_unix.cmi
add lib src/fut_unix.cmx	
add lib src/fut_unix.cma
add lib src/fut_unix.a
add lib src/fut_unix.cmxa
add lib src/fut_unix.cmxs

if [ "$JSOO" != "false" ]; then 
    add lib src/fut_jsoo.mli	
    add lib src/fut_jsoo.cmti
    add lib src/fut_jsoo.cmx 
    add lib src/fut_jsoo.cmi
    add lib src/fut_jsoo.cma
    add lib src/fut_jsoo.a
    add lib src/fut_jsoo.cmxa
    add lib src/fut_jsoo.cmxs
fi

add doc README.md
add doc CHANGES.md

build
install fut
